### ISSUE TITLE
behavior after open a file or click close button: minimized and stay in the tray 

### ISSUE THREAD

**Issue by GuShaocheng** [cboxdoerfer/fsearch#477] opened 2023-05-10 15:37 UTC
Hi developer,

I would like to keep fsearch always running.
Would you consider adding such behavior for it:
- click the close button but don't close it instead minimize it to the system tray
- open a file or folder successfully then minimize it to the tray

Thanks for your consideration,
All the best!

**Comment by nekohayo** [comment] 2024-01-20 15:35
Duplicate of #327, #487, #52. Please close this.

**Closed** 2024-01-21 11:44 UTC
Labels: feature_request
