### ISSUE TITLE
Invisible icon in panel and menu

### ISSUE THREAD

**Issue by Ghizza** [cboxdoerfer/fsearch#211] opened 2020-08-27 07:18 UTC
Hello, all of a sudden, the FSearch app icon disappeared from my panel and menu, or rather, it became "invisible".
The icon is actually "there", but its place looks empty. On mouse over, the area is highlighted, on click the app opens regularly.
I already unsuccessfully tried to:
- change the icon theme
- resize the panel
- resize the icons
- uninstall + install again FSearch app
- remove the icon and set it back again
- change desktop theme
I'm on: Linux Mint 20 x86_64 Cinnamon | ThinkPad E15 | Kernel: 5.4.0-42-generic | 1920x1080 | Numix icon theme | AMD ATI Radeon 540X/550X/630 / GPU: Intel UHD Graphics

**Comment by cboxdoerfer** [comment] 2020-08-27 14:49
Thank's for reporting. What language do you use on your system?

**Comment by Ghizza** [comment] 2020-08-27 16:00
Italian.
The screenshot below shows the issue better.
FSearch "invisible icon" lies in that "black hole" between the Nemo and Krusader icons.
![Schermata del 2020-08-13 18-18-09](https://user-images.githubusercontent.com/70313635/91465798-8c981a80-e88e-11ea-9e1c-bbacab1a89fd.png)

**Comment by cboxdoerfer** [comment] 2020-08-27 16:11
Thank's, can you try the following: 

* Copy `/usr/share/applications/fsearch.desktop` to `~/.local/share/applications/fsearch.desktop`
* Delete the line  starting with `Icon[it] ...` from the new file

Does this help? You might need to logout and login again, or maybe restart the system.

**Comment by cboxdoerfer** [comment] 2020-08-27 16:13
What's happening here is that the icon name was translated and then the system can't find the proper icon because they're all in english. I need to find a way to disable icon name localization somehow.

**Comment by Ghizza** [comment] 2020-08-27 17:29
Yes!
Problem solved. No need to restart.
Thank you very much. FSearch is arguably the app I use most on Linux!

**Comment by cboxdoerfer** [comment] 2020-08-27 17:35
Np, I'll keep the issue open until the issue is fixed in the translation process. It seems other languages are affected as well.

Nice to hear you like FSearch :)

**Comment by AtilioA** [comment] 2020-08-29 21:23
I can confirm that this is due to the icon name being translated. That '`system-search`' string needs to be ignored.

**Comment by cboxdoerfer** [comment] 2020-08-31 06:44
Fixed.

**Closed** 2020-08-31 06:44 UTC
