### ISSUE TITLE
Discarding changes at database include list

### ISSUE THREAD

**Issue by oktaycekmez** [cboxdoerfer/fsearch#97] opened 2017-09-09 08:33 UTC
I am making a modification at Preferences/database/include , for example deleting a folder from there and saving it and when I reopen include section, I am seeing the old folder still there. 
So it doesn't save the changes those made on include list.

I am using Ubuntu 16.0.4, and fsearch second beta release.

**Comment by cboxdoerfer** [comment] 2017-09-09 17:05
Can you try the latest build which is provided via the PPA? https://launchpad.net/~christian-boxdoerfer/+archive/ubuntu/fsearch-daily

**Comment by oktaycekmez** [comment] 2017-09-13 19:16
I couldn't delete my version, which command may remove fsearch?
I used the below instructions
https://github.com/cboxdoerfer/fsearch/wiki/Build-instructions

**Comment by cboxdoerfer** [comment] 2017-09-13 19:18
To uninstall fsearch move to the fsearch source directory and run `sudo make uninstall`.

**Comment by spsf64** [comment] 2017-09-15 13:26
I have the same problem, cannot delete included directories...
archlinux

**Comment by oktaycekmez** [comment] 2017-09-17 15:09
@cboxdoerfer I have tried your ppa but still same problem.

**Comment by cboxdoerfer** [comment] 2017-09-17 16:21
@oktaycekmez, can you provide a detailed step by step description how to reproduce the bug? I tried it again (even on Ubuntu 16.04) and changes in the include section always work as intended, so I can't reproduce it.

And of course  `sudo make uninstall` doesn't remove your config entries in `$HOME`, it only removes the software. If you want to remove the config (`~/.config/fsearch`) you have to manually remove it like with every other software.

**Comment by spsf64** [comment] 2017-10-10 14:09
@cboxdoerfer please take a look at this small video, maybe you can understand what is happening...

https://sourceforge.net/projects/arch-mod/files/fsearch.mp4/download

This is archlinux with XFCE
TIA

**Comment by cboxdoerfer** [comment] 2017-10-10 14:12
@spsf64 thanks, that's great. I'll try to figure out what's going wrong.

**Comment by cboxdoerfer** [comment] 2017-10-10 14:14
@spsf64, I can reproduce it 👍

**Comment by spsf64** [comment] 2017-10-10 14:17
@cboxdoerfer that is good! Now you can investigate further..
Thanks!

**Comment by cboxdoerfer** [comment] 2017-10-10 14:24
Should be fixed. :)

**Closed** 2017-10-10 14:24 UTC

**Comment by spsf64** [comment] 2017-10-10 14:29
@cboxdoerfer 
Wow! It works!
Just rebuilt the package from AUR/git, working 100%!
Probably @memoryleakx will be interested in this fix too..
Thanks a lot!
