### ISSUE TITLE
Remember column configuration - Date modified issue

### ISSUE THREAD

**Issue by smjure** [cboxdoerfer/fsearch#173] opened 2020-01-15 05:55 UTC
It would be good that fsearch opens as it was previously closed, including that the results are sorted according to "Date modified", newest first. But when ever I open the fserach, column configuration is "remembered" but not Date modified, it goes back to alphabetic file sort.

**Comment by cboxdoerfer** [comment] 2020-07-29 15:02
Closing, duplicate of #67

**Closed by cboxdoerfer** 2020-07-29 15:02 UTC
Labels: enhancement

**Comment by cboxdoerfer** [comment] 2020-08-02 19:48
Fixed.
