### ISSUE TITLE
Cannot include root directory "/" and get fsearch working

### ISSUE THREAD

**Issue by kupiqu** [cboxdoerfer/fsearch#68] opened 2017-03-06 17:10 UTC
Nothing is added to database if root directory `/` is included.

I'd like to add just `/` and then specifically exclude directories and files. This doesn't seem to work though...

**Comment by bartkmq** [comment] 2017-03-15 14:20
Can not confirm, works fine for me on Ubuntu 16.10 and archlinux with fsearch a15323172106ff9c62933ae97cd96c0d40b3fd22
![bildschirmfoto vom 2017-03-15 15-15-13](https://cloud.githubusercontent.com/assets/25273823/23952647/59e02602-0992-11e7-97a4-cfc40e36cd99.png)

What OS and fsearch version are you using?

**Comment by kupiqu** [comment] 2017-03-15 16:06
Yes, that's right, but at least in my case I had to do it directly in the config file, which by the way, it does not exist until one exits fsearch by first time.

That surely is a gtk thing but picking folders from the GUI is a bit of a pain and impossible for the "/" directory, as far as I could say... (but that may be just me, I'm not very efficient with that folder pickup, KDE user here, so I just ended up editing the config file directly).

To this regard, perhaps it would be nice to have all included dirs separated by commas in the same line of the config file (same for excluded dirs; you are currently doing this for excluded files).

**Comment by kupiqu** [comment] 2017-03-15 16:07
Ooops forgot, I use fsearch-trunk 0.1+272+9~ubuntu16.04.1 from an ubuntu ppa, KDE neon 16.04 user.

**Comment by cboxdoerfer** [comment] 2017-03-16 18:48
@kupiqu, you are right. The GTK+ file chooser dialog is quite a mess, I'll think of another way to add paths. Maybe with a simple text field with directory completion.

**Comment by marvingee** [comment] 2017-06-14 08:13
When I include root fsearch crashes while indexing.

**Comment by cboxdoerfer** [comment] 2017-06-14 08:58
@marvingee, can you launch fsearch from console and paste the output of it here when it crashes while indexing `/`?

I also have `/` indexed, but here it works just fine so I'm not sure what's going wrong.

**Comment by marvingee** [comment] 2017-06-14 09:20
Sure. When using the config including root:

    $ fsearch 
    loaded config file
    load location: /
    excluded directory: /media
    excluded directory: /mnt
    loaded db in:2719 ms
    enable action: update_database

So it found nothing. Then when i close

    ** (fsearch:9936): CRITICAL **: db_save_locations: assertion 'db->locations != NULL' failed
    clear locations

    ** (fsearch:9936): CRITICAL **: db_location_free_all: assertion 'db->locations != NULL' failed
    saved config file

When using the config including everything separately:

    $ fsearch
    loaded config file
    load location: /bin
    location num entries: 164
    load location: /boot
    location num entries: 581
    load location: /boot-sav
    location num entries: 4
    load location: /BootInfo
    location num entries: 4
    load location: /cdrom
    location num entries: 0
    load location: /dev
    location num entries: 591
    load location: /etc
    location num entries: 4396
    load location: /home
    load location: /lib
    location num entries: 14637
    load location: /lib64
    location num entries: 1
    load location: /opt
    location num entries: 3279
    load location: /proc
    location num entries: 236176
    load location: /root
    load location: /run
    location num entries: 977
    load location: /sbin
    location num entries: 225
    load location: /snap
    location num entries: 0
    load location: /srv
    location num entries: 0
    load location: /sys
    location num entries: 35116
    load location: /tmp
    load location: /usr
    location num entries: 937766
    load location: /var
    location num entries: 19105
    load location: /lost+found
    update list: 1253022
    start sorting
    finished sorting
    loaded db in:3379 ms
    enable action: update_database
    /home/marvingee/.config/fsearch/database/808dd192d3243666b6f1ad4f9bfeca4877ee059456c40851a93937331b26014c
    /home/marvingee/.config/fsearch/database/347a1e2537cc7aea90a4938443f967a544ea0e3f60fdc4cb45c3347a3df94bc9
    /home/marvingee/.config/fsearch/database/080e7059c28299677dc5681bda4d601d0e5965214bb6b4b5be81d5db55a17d62
    /home/marvingee/.config/fsearch/database/af05b733329c0469f52768a2ef3fa1bcc93b172cf7f8483f14e5c8d9bba23188
    /home/marvingee/.config/fsearch/database/dd848191a1b62b6e2d3a21f7df6663152e950bccb484356edfe4b1e7627c0a1e
    /home/marvingee/.config/fsearch/database/938b99e3330802a9290b64452b1b303a7efa94dd8f5fc86b6c941cf0644ce220
    /home/marvingee/.config/fsearch/database/2824684de3d1a19390ca88cf826e77c6f750657e552edb83d466666c37521a08
    /home/marvingee/.config/fsearch/database/4b2f4473e24574e8f7e12b6eaeb2210f9987d5836ca53404b80edb821c973b37
    /home/marvingee/.config/fsearch/database/85a751691bd9e406125958dcd9e2f01044ccf804fcd2ebe122617af265ad540a
    /home/marvingee/.config/fsearch/database/cbcdfaeb37659981a3e96b9ec2000c67c9fa42b452cb26c41db886fca95f6ed0
    /home/marvingee/.config/fsearch/database/71ad1dfa1de556decbd6d7314196552e349d66067b49ab6bf8d4865faa663441
    /home/marvingee/.config/fsearch/database/b3d46fe883f343fe8d86cceea5141710f5cf97ab3b21a0d813982e1155d4c717
    /home/marvingee/.config/fsearch/database/af686b9ed0603971c45065a1ff21b215c6b29858af059f4f98fd9f91c36fad73
    /home/marvingee/.config/fsearch/database/fce74e2ba927fd1ab56bced67740ddd2b66854d58a409de53163f769c78c9f68
    /home/marvingee/.config/fsearch/database/a3d9ac4fdee9c2424e2fe95742f45f7d5134426aee734e778201f5db161741cc
    /home/marvingee/.config/fsearch/database/0bb7b4e45ea451fc58b3444bace01ea87ad00efe015a186bf5bc90a2e830f32e
    /home/marvingee/.config/fsearch/database/894d731f69bb61966f9ca61d0762a37bc542e0bbe4ba7c931fc75129c2229961
    /home/marvingee/.config/fsearch/database/c309689ef6f2432e55b81fdb6e139e2857ba1aba16ea4270daa3f5ab68181cd3
    clear locations
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    free location
    saved config file

Interestingly as you can see it fails to index /home when just including /home as the location, just like with root. When including /home/marvingee it works.

    load location: /home/marvingee
    location num entries: 237313

**Comment by cboxdoerfer** [comment] 2017-06-14 09:49
This helps a lot. So something goes wrong when indexing `/home` and hat's probably why indexing `/` fails. Can you paste the output of `ls -l /` and `ls -l /home`?

**Comment by marvingee** [comment] 2017-06-14 09:58
$ ls -l
    total 20
    drwxr-xr-x 59 marvingee marvingee  4096 Jun 14 11:54 marvingee
    drwx------  2 root      root      16384 Jul 22  2016 lost+found

**Comment by cboxdoerfer** [comment] 2017-06-14 10:23
I just pushed a small commit which prevents indexing from completely failing when one of the contents in the root dir can't be indexed. This should prevent the crashing and maybe also the issue with indexing `/home`. I also triggered a new PPA build, which should be ready in a few minutes, then you can update to the latest version to verify if it fixed the issue.

**Comment by marvingee** [comment] 2017-06-14 14:51
Well it works mostly now with `/`. Only difference is, that 1,714,421 entries get found including `/` only and 1,721,224 when including all folders under `/` manually.

**Comment by cboxdoerfer** [comment] 2017-06-14 16:56
Hm, yeah that is weird. I'm trying to reproduce this somehow.

**Comment by cboxdoerfer** [comment] 2021-07-17 16:26
Closing, since I can't reproduce it. If it's still happening please let me know and we'll reopen it.

**Closed by cboxdoerfer** 2021-07-17 16:26 UTC
Labels: enhancement

**Comment by mohsentux** [comment] 2022-03-17 12:22
where is the config file for fsearch??
I'm having the same issue with opensuse kde leap

**Comment by cboxdoerfer** [comment] 2022-03-17 12:27
What happens after you add `/` to the included folders and click OK?

The config is in `~/.config/fsearch/fsearch conf`

**Comment by mohsentux** [comment] 2022-04-10 14:25
I used the GUI didn't work. Searched the net. realized on none Gnome systems it's to be expected and someone pointed out the location of the config file itself. I'm not sure if it can be solved. too many distros too many variables.
UNLESS you change the gui to Qt

**Comment by cboxdoerfer** [comment] 2022-04-10 14:51
> I used the GUI didn't work. 

At what step didn't it work? Like can't you select the root folder in the file chooser dialog, or does scanning root not work or something else?
