### ISSUE TITLE
Only Update Changes

### ISSUE THREAD

**Issue by minutesinch** [cboxdoerfer/fsearch#184] opened 2020-04-21 20:11 UTC
I have an idea for improving users usages and avoid damaging to users ssd and wasting time on big hdd, so you must add an option, let users enable it from preferences(and can be automatically enabled when program found users use ssd and/or lagrer hdd(biger than 500GB for example) or even enabled by default;and this option only watch files/and folders changes and update databse.
not need full database update, this is very helpful and i see this program can be better than search everything.
regard

**Comment by cboxdoerfer** [comment] 2020-07-29 18:14
Duplicate of #138 and #26, closing.

**Closed** 2020-07-29 18:14 UTC
Labels: enhancement
