### ISSUE TITLE
[BUG] found characters are not applyed bold

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#329] opened 2021-12-29 16:04 UTC
**Describe the bug**
When I use not Regex for searching, then the searched characters are marked in the path and files in bold font. When I do the same with Regex there are some cases, where the characters are not marked bold.

**To Reproduce**
You can see in the picture an example:
![ksnip_20211229-165607](https://user-images.githubusercontent.com/13977359/147680856-38945095-1e67-48b8-9dbe-5063e9b9018f.jpg)

**Expected behavior**
My expectation is, that the path is bold and also "558" is bold. But all is in normal font.

**Desktop (please complete the following information):**
 - OS: MX Linux 19.4
 - MX package installer
 - Version 0.1

Edit: To be more precise: This seems to happen, when one Regex string is in the path and the other in the file name. If both is in the file name or both is in the path, then the characters are marked bod.

**Comment by cboxdoerfer** [comment] 2021-12-30 14:13
Yes, that's a known issue when the highlighted part applies to both file name and path. It's not even exclusive to regex mode, it also happens with wildcards.

I'll see what I can do about it. Seems like it should be relatively easy to fix.

**Comment by Golddouble** [comment] 2022-01-01 14:58
A)
It looks like I have found another case, where FSearch does not mark correct bold, what it has found:
![ksnip_20220101-153704](https://user-images.githubusercontent.com/13977359/147852995-d9a80b0b-895e-43fd-bca0-0a1c0aa62121.jpg)

Shouldn't both "a" be bold in "aas1901" ?

**Comment by Golddouble** [comment] 2022-01-04 12:58
This is a further example:
![ksnip_20220104-135636](https://user-images.githubusercontent.com/13977359/148062579-efac1876-1d6c-4bfb-b5be-608c2b776fa0.jpg)

**Comment by Golddouble** [comment] 2022-01-04 16:07
Is this result really as it should be?:
![ksnip_20220104-170340](https://user-images.githubusercontent.com/13977359/148087763-b189fd67-5e2d-4566-a5a6-8871fa7b6378.jpg)

My expectation was, that it would not find for example `$I8CTTC9.pdf` because the regex command says do find files that do not have "p" or "d" or "f" in its name, but `$I8CTTC9.pdf` has for example a "p" in its name. So I guess this file should not have been found?

I could be wrong. Do I miss anything?

**Comment by cboxdoerfer** [comment] 2022-01-04 17:33
> This is a further example: ![ksnip_20220104-135636](https://user-images.githubusercontent.com/13977359/148062579-efac1876-1d6c-4bfb-b5be-608c2b776fa0.jpg)

This looks fine to me, what's the issue there?

**Comment by cboxdoerfer** [comment] 2022-01-04 17:56
> Is this result really as it should be?: ![ksnip_20220104-170340](https://user-images.githubusercontent.com/13977359/148087763-b189fd67-5e2d-4566-a5a6-8871fa7b6378.jpg)

Yes.

> My expectation was, that it would not find for example `$I8CTTC9.pdf` because the regex command says: "Do find files, that do not have "p" or "d" or "f" in its name". But `$I8CTTC9.pdf` has for example a "p" in its name. So I guess this file should not have been found?

No, the regex says: Match any character multiple times followed by a character which is not `p`, `d` or `f`. So in your example the `.*` matches `$$I8CTTC9` and `[^pdf]`the following `.`, because it's neither `p`, `d` or `f`.

**Comment by cboxdoerfer** [comment] 2022-01-04 17:59
> It looks like I have found another case, where FSearch does not mark correct bold, what it has found: ![ksnip_20220101-153704](https://user-images.githubusercontent.com/13977359/147852995-d9a80b0b-895e-43fd-bca0-0a1c0aa62121.jpg)
> 
> Shouldn't both "a" be bold in "aas1901" ?

Yes, I can confirm that. I'll have a look at it. My guess is that this is caused by the fact that FSearch uses different regular expression libraries for matching and highlighting.

**Comment by Golddouble** [comment] 2022-01-04 19:15
Thank you for your answers.

relating to the example with `.*[^pdf]`:
Oh yes, I see. Thank you. Of course this works in FSearch as it should. Sorry.

relating to the example with 



> > This is a further example: ![ksnip_20220104-135636](https://user-images.githubusercontent.com/13977359/148062579-efac1876-1d6c-4bfb-b5be-608c2b776fa0.jpg)
> 
> This looks fine to me, what's the issue there?

In this example Regex gives results with "ab" and "ac". So my expectation was, that in "ab" "a" is marked bold and also "b". And in "ac", that "a" is marked bold and also "c" is marked bold. But FSearch does only mark "b" bold in "ab". And only "c" in "ac".

**Comment by cboxdoerfer** [comment] 2022-01-05 14:40
> Thank you for your answers.

> relating to the example with .*[^pdf]:
> Oh yes, I see. Thank you. Of course this works in FSearch as it should. Sorry.

No problem. If you really want to exclude files with certain patterns, you should look at negative look-ahead regular expressions. For example to list everything except PDF files, you can use something like this: `^(?!.*\.pdf$)`

> In this example Regex gives results with "ab" and "ac". So my expectation was, that in "ab" "a" is marked bold and also "b". And in "ac", that "a" is marked bold and also "c" is marked bold. But FSearch does only mark "b" bold in "ab". And only "c" in "ac".

Ah yes, you're right. That's definitely a bug. Thanks!

**Comment by cboxdoerfer** [comment] 2022-07-17 17:47
All those issues (mismatching regex search results and highlights and issues when highlighting applies to both path and name) have already been fixed in the 0.2alpha builds. I'm planing to release 0.2 at the end of next month.

**Comment by cboxdoerfer** [comment] 2022-08-20 16:31
0.2 with the fixes is no available. Closing the issue.

**Closed by cboxdoerfer** 2022-08-20 16:31 UTC
Labels: bug
