### ISSUE TITLE
Drag and drop files from fsearch

### ISSUE THREAD

**Issue by petric3** [cboxdoerfer/fsearch#175] opened 2020-01-18 12:52 UTC
It'd be awesome if it'd be possible to drag and drop searched files directly from fsearch. For example, many times I search for a file which I have to drop into email, but cannot do that, so have to open the folder of the searched file, locate it and drag it into email. Similar is for dragging files into other folders, gDrive, programs for sending it, etc. Drag and drop (basically copying) would be very useful feature. Thank you :) FYI: I use fsearch in Ubuntu 18.04.

**Comment by cboxdoerfer** [comment] 2020-01-18 16:21
Duplicate of #11

**Closed** 2020-01-18 16:21 UTC
