### ISSUE TITLE
[BUG] Ubuntu 22.04 PPA has a broken dependencie

### ISSUE THREAD

**Issue by joytrekker** [cboxdoerfer/fsearch#350] opened 2022-04-23 04:32 UTC
When installing fseach on Ubuntu 22.04 from the PPA there is a broken dependencie that prevents installing.
Using `sudo apt install fsearch` returns:

The following packages have unmet dependencies:
 fsearch : Depends: libicu67 (>= 67.1-1~) but it is not installable

**Comment by cboxdoerfer** [comment] 2022-04-23 05:40
You're attempting to install an FSearch package which was built for an older Ubuntu release. This sounds like a duplicate of #347 which means you most likely upgraded from a previous Ubuntu release but didn't upgrade the PPA.

**Comment by joytrekker** [comment] 2022-04-23 05:50
This is a fresh install of Ubuntu 22.04. This is the PPA I'm using
`deb https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-stable/ubuntu/ jammy main`

`apt search fsearch` returns

`fsearch/jammy 0.1.2-0~202202121237~ubuntu22.04.1 amd64
  A fast graphical file search utility
`
Looks like the last build was 2022-02-12?

**Comment by cboxdoerfer** [comment] 2022-04-23 05:57
Interesting, then Canonical probably updated the icu package in the last week during the development process. I triggered a rebuild which should fix the issue. The new package should be ready in a couple of hours. Thank you!

**Comment by joytrekker** [comment] 2022-04-23 06:15
Ok I will try it again later.
 
Sort of related.... the daily dev PPA currently does not have a release file for Ubuntu 22.04
After adding the daily PPA  `apt update` returns

```
Err:11 https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-daily/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/christian-boxdoerfer/fsearch-daily/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by cboxdoerfer** [comment] 2022-04-23 06:20
Thx, daily PPA for 22.04 has now been added and the build is running.

**Comment by joytrekker** [comment] 2022-04-23 20:57
This can be closed. 
I just installed from the PPA. Everything is working now.
Thanks

**Closed** 2022-04-27 18:40 UTC
Labels: bug
