### ISSUE TITLE
[feature request] set search result limit greater than 1000, export results to file, import catalog to another fsearch on another computer?

### ISSUE THREAD

**Issue by kocoman1** [cboxdoerfer/fsearch#249] opened 2021-03-10 00:35 UTC
[feature request]

1) set search result limit greater than 1000, 
2)export search results to file, 

3)import catalog to another fsearch on another computer?
(for searching in a faster computer)

4) move around the colomns like move "date" to be next to "filename" by mouse?

thx

**Comment by cboxdoerfer** [comment] 2021-04-02 10:38
> set search result limit greater than 1000,

That's already possible in **Preferences -> Search -> Limit number of results**. But right now increasing the number can lead to performance issues, because the GtkTreeView which is used to display the results doesn't work well with many entries. I'm currently working on a new listview (found in the `listview`) where those performance issues are fixed and all results will be displayed at any time.

> export search results to file

Already on my todo list, but it's a low priority for me. Unless someone else implements it, it will take months or even years until I get to it.

> import catalog to another fsearch on another computer?

I haven't tested it, but this might already be possible by copying the database and config directory, but making that more straightforward might be a good idea. However, like before that's a low priority for me.

> move around the colomns like move "date" to be next to "filename" by mouse?

This will be possible with the new listview.

**Comment by cboxdoerfer** [comment] 2021-07-17 16:47
1. is fixed with the new listview (it always shows all results)
2. duplicate of #112
3. already works by copying the database file
4. duplicate of #75

Closing.

**Closed by cboxdoerfer** 2021-07-17 16:47 UTC
