### ISSUE TITLE
In Preferences to have the possibility to chose if Close Window button (x) only hide (minimize) the window 

### ISSUE THREAD

**Issue by silviulaurentiu** [cboxdoerfer/fsearch#507] opened 2023-09-26 11:39 UTC

**Comment by nekohayo** [comment] 2024-01-20 15:25
As per the suggestions in #392 and #416, I would recommend against this added complexity.

**Comment by nekohayo** [comment] 2024-01-20 15:35
Also it is a duplicate of #327, #487, #52. At this point I would suggest closing this ticket.

**Comment by cboxdoerfer** [comment] 2024-01-21 11:40
Yes, that'll be covered by the tray icon feature.

**Closed by cboxdoerfer** 2024-01-21 11:40 UTC
Labels: feature_request
