### ISSUE TITLE
"remember column configuration" does not work for sorting

### ISSUE THREAD

**Issue by sdx23** [cboxdoerfer/fsearch#118] opened 2017-12-14 16:19 UTC
The sorting preference of columns is not remembered.

Steps to reproduce:
1. Edit Preferences, check box at "remember column configuration"
2. Change sorting, e.g. click twice on "date" to sort for most recent date (most used setting for me - maybe even a good default)
3. Close fsearch
4. Open fsearch again, sorting is by name

Version information
0.1 beta

**Comment by cboxdoerfer** [comment] 2018-01-03 10:52
Yes, remembering column sort order is not implemented yet. Added to todo list.

**Comment by cboxdoerfer** [comment] 2018-01-03 11:01
Duplicate of #67

**Closed by cboxdoerfer** 2018-01-03 11:01 UTC
Labels: enhancement
