### ISSUE TITLE
[BUG] Files are indexed twice from folder softlink

### ISSUE THREAD

**Issue by ShrirajHegde** [cboxdoerfer/fsearch#245] opened 2021-02-11 05:11 UTC
**Describe the bug**

**To Reproduce**
1. Create a softlink to a directory in home / some accessible location ( the specific directory should also be included in indexing)
2. Update db
3. Search for files in softlinked folder
4. Check same directory indexed multiple times

**Expected behavior**
Exclude same files which end up indexed twice due to softlinks + additional option to not go inside softlinks

**Screenshots**
![image](https://user-images.githubusercontent.com/66936172/107603946-74596380-6c54-11eb-91a5-68ed23e51f9d.png)
indexed twice and even softlink is indexed (which is expected behavior)
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - How you installed FSearch - PPA
 - Version [output of `fsearch --version`] -FSearch 0.1beta4
 - Output of `localectl status` ;
 ```
 - System Locale: LANG=en_US.UTF-8
                  LANGUAGE=en_US:en
                  LC_NUMERIC=en_IN.UTF-8
                  LC_TIME=en_IN.UTF-8
                  LC_MONETARY=en_IN.UTF-8
                  LC_PAPER=en_IN.UTF-8
                  LC_NAME=en_IN.UTF-8
                  LC_ADDRESS=en_IN.UTF-8
                  LC_TELEPHONE=en_IN.UTF-8
                  LC_MEASUREMENT=en_IN.UTF-8
                  LC_IDENTIFICATION=en_IN.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
```

**Additional context**
Adding multiple softlinks makes multiple search results

**Comment by cboxdoerfer** [comment] 2021-06-18 09:42
Sorry for the late response. I'm having trouble to reproduce the issue. On my system symbolic links are not followed (which is the intended behavior) so I don't get any duplicated results. Are you sure that the destination is not included twice in the database settings?

**Comment by ShrirajHegde** [comment] 2021-06-19 05:55
I have switched to Fedora, Is there any RPM build?

**Comment by ShrirajHegde** [comment] 2021-06-19 06:15
ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home%3A/woelfel/openSUSE_Leap_15.0/src/fsearch-0.1beta2-lp150.2.1.src.rpm

Used this RPM, the issue doesn't seem to exist.

![image](https://user-images.githubusercontent.com/66936172/122632941-7dbb7680-d0f3-11eb-9ed5-cef162c1dead.png)

Because /home and /media/../NTFS_drive are included and home has symlinks to directories in NTFS_drive

**Comment by cboxdoerfer** [comment] 2021-06-19 06:26
No, afaik there are no up to date RPM builds, at least no official ones. The one you tried looks pretty outdated.

I'll see if I can setup an automatic build process for Fedora and report back to you.

What would be helpful either way would be the content of `~/.config/fsearch` if you still have access to it and the output of `ls -l` in the directories where the symbolic link sits and its destination. Of course you can omit any lines etc., if they contain any private information.

**Comment by cboxdoerfer** [comment] 2021-06-19 06:33
@inori39 just informed me thst they made a repository for Fedora builds: https://copr.fedorainfracloud.org/coprs/inori39/fsearch/

**Comment by ShrirajHegde** [comment] 2021-06-19 06:44
Yes, works well, 
![image](https://user-images.githubusercontent.com/66936172/122633618-1d2e3880-d0f7-11eb-9080-69e33810940a.png)

```
[Database]
update_database_on_launch=false
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/media/srj/Shriraj_Storage
location_2=/media/srj/ssd-storage
location_3=/home/srj
```
As far as Fedora goes, it is working perfectly!

I have the Ubuntu system I used when opening the issue, I will check in that and update you.

**Comment by cboxdoerfer** [comment] 2021-07-17 16:37
I'll close this issue since it seems to be fixed. If not, let me know and I'll reopen it again.

**Closed by cboxdoerfer** 2021-07-17 16:37 UTC
Labels: bug
