### ISSUE TITLE
[Feature Request] Support minimum into tray as a icon? 

### ISSUE THREAD

**Issue by zw963** [cboxdoerfer/fsearch#524] opened 2023-12-21 16:53 UTC
Just like following screenshot which works on my GNOME 45.

![image](https://github.com/cboxdoerfer/fsearch/assets/549126/8accab66-bcd5-4d35-ad42-4728c7ed0e10)

Then i can open FSearch more quickly anytime when i want with just mouse click, and keeping update database use `references -> Database -> Update every` settings.

Anyway, i can update database use crontab, and start FSearch every time i want to use it, then close it after done, but i consider keeping it living as a tray icon is better.

Thanks.

**Comment by zw963** [comment] 2023-12-24 06:41
Another workaround is, fsearch include a oneshot service, like this:

1. fsearch.service

```
[Unit]
Description=fsearch

[Service]
Type=oneshot
ExecStart=/usr/sbin/fsearch -u
```

Then, include a timer service with same name.

fsearch.timer, run every 10 minutes.

```
[Unit]
Description=Run fsearch update database periodically

[Timer]
OnCalendar=*-*-* *:00/10:00
RandomizedDelaySec=20
[Install]
WantedBy=timers.target
```

**Comment by nekohayo** [comment] 2024-01-20 15:34
Duplicate of #327, #487, #52. Please close this.

**Closed** 2024-01-20 17:02 UTC
Labels: feature_request
