### ISSUE TITLE
Segfault when excluding hidden files while initial scan is running

### ISSUE THREAD

**Issue by flopp** [cboxdoerfer/fsearch#148] opened 2018-11-20 19:44 UTC
Version:
fsearch 0.1+362+9~ubuntu18.04.1 from the fsearch-daily PPA on Ubuntu 18.04.1

Reproduce:

1. Start fsearch for the first time
2. Add some include dirs via the preferences dialog, click "OK" to close dialog => scan starts
3. Observe that hidden files are being indexed => go to the preferences dialog (while the scan is running), select "Exclude hidden files and folders", click "OK" to close dialog => Segfault

Console output:
```
$ fsearch
load config failed: No such file or directory

loaded db in:0 ms
enable action: update_database
### here, include dirs are added via the preferences dialog ###
disable action: update_database
update
clear locations

** (fsearch:23436): CRITICAL **: 20:33:00.203: db_location_free_all: assertion 'db->locations != NULL' failed
load location: /home/florian
### here, hidden files are excluded via the preferences dialog ###
disable action: update_database
update
clear locations

** (fsearch:23436): CRITICAL **: 20:33:10.752: db_location_free_all: assertion 'db->locations != NULL' failed
Segmentation fault
```

**Comment by cboxdoerfer** [comment] 2020-07-26 16:31
Thanks for reporting and I'm sorry it took so long, but the issue is now fixed!

**Closed by cboxdoerfer** 2020-07-26 16:31 UTC
Labels: bug, confirmed
