### ISSUE TITLE
Open/Open With limited to 10 items.

### ISSUE THREAD

**Issue by NDM78** [cboxdoerfer/fsearch#111] opened 2017-10-27 16:40 UTC
The context menu "Open" and "Open With" appear to be limited to 10 or fewer items.

Selecting "Open" with more than 10 items selected appears to do nothing while using "Open With" runs the program but doesn't pass the selected files to it.

It would be great if the limit could be increased or made user configurable.

Thanks.

**Comment by cboxdoerfer** [comment] 2017-10-30 11:07
Yes, this arbitrary limit without any way to disable it sucks. I'll fix it.

**Comment by cboxdoerfer** [comment] 2020-07-25 10:13
It took a while (almost three years) but the issue is now fixed. ^^

**Closed by cboxdoerfer** 2020-07-25 10:13 UTC
