### ISSUE TITLE
[feature request] mac version

### ISSUE THREAD

**Issue by kocoman1** [cboxdoerfer/fsearch#248] opened 2021-03-10 00:32 UTC
[feature request] mac version.
Will a version for mac be on the roadmap? thx

**Comment by cboxdoerfer** [comment] 2021-03-10 06:36
No, I don't know any simple way to develop for macOS without having access to a Mac, which I don't have.

So unless someone else starts to work on a macOS port I'm afraid this won't happen.

**Comment by cboxdoerfer** [comment] 2021-07-17 16:48
Duplicate of #7 

Closing.

**Closed by cboxdoerfer** 2021-07-17 16:48 UTC
