### ISSUE TITLE
Stable Release 0.1

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#286] opened 2021-09-15 07:45 UTC
> I didn't tag a new release, because the next release is going to be the stable 0.1 release (hopefully end of Sep or start of Oct 2020). 

_Originally posted by @cboxdoerfer in https://github.com/cboxdoerfer/fsearch/issues/201#issuecomment-684915325_

Hello,
Is there in the meantime a stable 0.1 release?
I have only found a Beta 4.

All points in https://github.com/cboxdoerfer/fsearch/wiki/Roadmap are checked.

(?)

**Comment by cboxdoerfer** [comment] 2021-09-15 13:29
No, there hasn't been a stable release yet. The main reason why I keep delaying it is because I found a few shortcomings and missing features in the database format, which I'd rather fix before the release. The issue is that those database format updates require a rescan of all folders, which might be annoying for users.

But maybe I'm just putting too much thought into it, after all the format probably is going to change again in the future, and most users wouldn't mind a database upgrade once every couple of years. What do you think?

**Comment by Golddouble** [comment] 2021-09-15 15:37
Thank you for this interesting background information.

> The issue is that those database format updates require a rescan of all folders, which might be annoying for users.

Quote: "require a rescan of all folders": 
Do you speak about the function "menu-> file-> update database" ? And are you worried that the user will be irritated if he has to run "menu-> file-> update database" again when a further "preview" is published after the "stable release"? 

If yes, I guess this would never be a problem, because users do use this function every day. And a lot of them use "auto database update" when starting FSearch. So when anybody installs a new Fsearch preview, he will anyway update the database.

**Comment by cboxdoerfer** [comment] 2021-09-15 18:35
> Quote: "require a rescan of all folders":
Do you speak about the function "menu-> file-> update database" ? And are you worried that the user will be irritated if he has to run "menu-> file-> update database" again when a further "preview" is published after the "stable release"?

Yes, and the fact that they can't search in the old database until the scan completes.

> If yes, I guess this would never be a problem, because users do use this function every day. And a lot of them use "auto database update" when starting FSearch. So when anybody installs a new Fsearch preview, he will anyway update the database.

Hm, yes I guess you're right. I'm going to fix some minor bugs this weekend and then prepare the release and we'll see how it goes.

**Comment by cboxdoerfer** [comment] 2021-09-30 16:47
0.1 is not out. Closing.

**Closed by cboxdoerfer** 2021-09-30 16:47 UTC
