### ISSUE TITLE
[BUG] Column widths are not adjustable nor movable

### ISSUE THREAD

**Issue by kelmankenberg** [cboxdoerfer/fsearch#344] opened 2022-03-07 15:05 UTC
**Describe the bug**
It is not possible to resize the width of any columns, nor move the column order regardless of the size of the FSearch window.

**Expected behavior**
I would expect to be able to:
- resize the columns in order to view the values without having to hover over an item (tooltip works well)
- move the left to right order of the columns to suit my preference

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon
 - Cinnamon Version 5.2.7
 - Kernal 5.4.0.1.100-generic
 - How you installed FSearch: PPA
 - Version 0.1.2
 - Output of `localectl status`
    System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105

**Comment by cboxdoerfer** [comment] 2022-03-07 15:54
> resize the columns in order to view the values without having to hover over an item (tooltip works well)

This is already supported and works as expected on all of my test systems. When you hover between two columns the cursor should change it's appearance to a double-arrow and then you should be able to resize columns. Can you describe what happens in your case?

> move the left to right order of the columns to suit my preference

That's not implemented yet, but it's on my todo list. Maybe it'll be ready for the next 0.2 release.

**Comment by kelmankenberg** [comment] 2022-03-07 16:14
Thanks for the quick reply.
When I hover over between two column headers, the cursor does not change.
Here is a screen capture to show you.

**Comment by cboxdoerfer** [comment] 2022-03-07 16:45
The screen capture isn't there. In case you sent it as an email attachment, I'm not sure if GitHub supports that.

**Comment by kelmankenberg** [comment] 2022-03-07 16:59
https://user-images.githubusercontent.com/27739928/157081440-5ac4b433-7b5f-4438-8dc5-769502dced44.mp4

**Comment by cboxdoerfer** [comment] 2022-03-07 18:28
Do you by any chance use a high-dpi screen with scaling enabled? I was just able to reproduce this bug when UI scaling was active.

**Comment by cboxdoerfer** [comment] 2022-03-07 18:30
The resizing still works, but the mouse cursor isn't updated.

**Comment by kelmankenberg** [comment] 2022-03-07 19:28
No, I use Automatic DPI
![System Settings 2022-03-07 13-27-04](https://user-images.githubusercontent.com/27739928/157104141-69f0f7b0-5db7-4611-8651-4fe1afce4fdd.png)

**Comment by kelmankenberg** [comment] 2022-03-07 22:17
Yes, it does.

**Comment by kelmankenberg** [comment] 2022-03-09 18:07
Also, I thought maybe resizing the window and selecting the **Remember window size** preference would at least be a workaround, but that only results in a lot of space on the right side of the window.

**Comment by kelmankenberg** [comment] 2022-03-16 14:58
https://user-images.githubusercontent.com/27739928/158619756-cbb29544-9822-4ee6-aefc-dd014145b76c.mp4

Here is the same result from a different user account. I may try to completely remove and reinstall FSearch.

**Comment by cboxdoerfer** [comment] 2022-03-16 15:27
Does clicking on the headers work, to sort the results?

**Comment by kelmankenberg** [comment] 2022-03-16 16:13
Yes, clicking the headers sorts ascending and descending as expected.

**Comment by kelmankenberg** [comment] 2022-03-16 17:00
FWIW: I just spun up a Linux Mint 20.3 VM (Windows host) and I have the same issue there.

**Comment by cboxdoerfer** [comment] 2022-03-17 07:59
@kelmankenberg thx for testing that. This is such a weird issue, because I can't seem to reproduce it. I'll probably prepare a special debug build with some console output for you, to get a better idea what's going wrong.

**Comment by kelmankenberg** [comment] 2022-03-17 13:35
Sure.  Anything I can do to help, let me know.  Like you, I was looking for a good Linux solution for Everything. FSearch is the closest I've found.  Thanks for the app.

**Comment by cboxdoerfer** [comment] 2022-03-17 17:10
In the meantime, can you try the following. Hover with the mouse slightly to the left or right above the column separator:
![fsearch_bug](https://user-images.githubusercontent.com/6108388/158855256-0a3af692-72fd-4283-968a-cf66fdaca2c5.png)

Then try to resize it by click and drag. You might need try it a few times at different spots, since it's a little tricky to hit the right area without the visual clue from the mouse cursor. Does resizing then work? If so, then it's only an issue with the cursor not updating properly, otherwise the resize area is probably messed.

**Comment by kelmankenberg** [comment] 2022-03-17 19:11
Actually, that does work. There is about a 1 or 2 pixel wide area there that I can grab, but it's real tricky.
On the VM, I've uninstalled FSearch using the Software Manager, then attempted to install using the terminal commands:

- sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-daily
- sudo apt-get update && sudo apt install fsearch-trunk

This did not complete, ending in the following:

Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fsearch-trunk : Depends: fsearch but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by cboxdoerfer** [comment] 2022-03-17 19:17
The package is called `fsearch` so instead of running `sudo apt install fsearch-trunk` you need to run `sudo apt install fsearch`

**Comment by cboxdoerfer** [comment] 2022-03-17 19:26
And on your real PC you might want to use the PPA with the release builds: https://launchpad.net/~christian-boxdoerfer/+archive/ubuntu/fsearch-stable

Your VM is using the development PPA with the commands you posted.

**Comment by kelmankenberg** [comment] 2022-03-17 19:52
That took care of the issue.  Thanks for walking me through this, and I hope you benefitted as well.
![Screenshot from 2022-03-17 14-51-49](https://user-images.githubusercontent.com/27739928/158884356-3097abf0-ba67-412f-9c6a-1ed12ff551df.png)

**Comment by cboxdoerfer** [comment] 2022-03-18 17:24
> That took care of the issue. Thanks for walking me through this, and I hope you benefitted as well.

Nice! Yes, it brought the cursor issue with the Flatpak version to my attention and I've just updated the Flatpak to use the GNOME runtime, where this issue should be fixed. So in a day or so the version from the software center should show the correct mouse cursor as well.

**Closed by cboxdoerfer** 2022-03-18 17:24 UTC
Labels: bug
