### ISSUE TITLE
I can not enter Cyrillic characters in the search field

### ISSUE THREAD

**Issue by artomberus** [cboxdoerfer/fsearch#228] opened 2020-10-20 20:18 UTC
(fsearch:4069): GLib-CRITICAL **: 22:48:06.999: g_utf8_strdown: assertion 'str != NULL' failed
Segmentation fault

The error began to appear after one of the updates, everything worked before.  I can still search using Latin characters, but when I enter Cyrillic, it crashes.

Elementary OS 5.1.7
Linux 5.4.0-52-lowlatency

The bug persists on the latest version.

**Comment by veksha** [comment] 2020-10-20 20:43
can't reproduce on my side

```
> fsearch --version
FSearch 0.1beta4.433-d18b
```

**Comment by cboxdoerfer** [comment] 2020-10-20 20:52
I can't reproduce it either. Can you post an example search text that causes the bug? Also what system language do you use?

**Comment by artomberus** [comment] 2020-10-21 05:20
> I can't reproduce it either. Can you post an example search text that causes the bug? Also what system language do you use?
System language is Russian.
When I enter the first character (any) of the Cyrillic characters in the search field, the window closes, the program displays an error in the terminal.

[08:16:49] dmitry@ASUS-X540UBR:~$ fsearch
[config] loading...
[config] loaded in 0,178000 ms
[application] disable action: update_database
[application] enable action: cancel_update_database
[application] disable action: update_database
[database_read_file] database version=0.1
[database_read_file] reached root node. done
[database_load] finished with 234092 of 234092 items successfully read
[database_update_list] create list for 234092 entries
[database_update_list] updated list
[database_update] finished in 109,84 ms
[application] enable action: cancel_update_database
[database_scan] scan location: /home/dmitry
[database_ref] increased to: 2
[search] 
[database_ref] increased to: 3
[database_unref] dropped to: 2
[database_ref] increased to: 3
[database_unref] dropped to: 2
[database_unref] dropped to: 1
[database_scan] /home/dmitry scanned with 230550 entries
[database_build_list] create list for 230550 entries
[database] sorting...
[database] sorted
[database_build_list] list created
[database_save] saving /home/dmitry to /home/dmitry/.local/share/fsearch/database/77b8308dab970fc3256b0889353c3fb3b76a29c2f65b8eae2707ad6c64b23009
[database_save] saved /home/dmitry/.local/share/fsearch/database/77b8308dab970fc3256b0889353c3fb3b76a29c2f65b8eae2707ad6c64b23009
[database_update] finished in 70,07 ms
[database_unref] dropped to: 0
[database_free] freeing...
[database_location_free_all] freeing...
[database_location_free_all] freed
[database_free] freed
[application] enable action: update_database
[application] disable action: cancel_update_database
[database_ref] increased to: 2
[search] 
[database_ref] increased to: 3
[database_unref] dropped to: 2
[database_ref] increased to: 3
[database_unref] dropped to: 2
[database_unref] dropped to: 1
[database_ref] increased to: 2
[search] ы
[search] token 0: ы

(fsearch:19052): GLib-CRITICAL **: 08:17:24.339: g_utf8_strdown: assertion 'str != NULL' failed
Ошибка сегментирования
[08:17:24] dmitry@ASUS-X540UBR:~$ 

This happens with any character in Russian: а, о, э, и. ы, у, ю, з, ш, щ, ф etc.

**Comment by cboxdoerfer** [comment] 2020-10-21 17:26
Hm, this is weird, I still can't reproduce it. Basically what's going on is that the text you entered is treated as invalid utf8.

Do you use the same layout and system language on both Xubuntu 20.04 and Elementary OS?

**Comment by cboxdoerfer** [comment] 2020-10-21 18:27
I just made a small modification which will likely fix the crash but I'm not sure if you get the correct search results. The PPA will receive the fix in the following 24 hours. In the meantime I'm also trying to reproduce it with Elementary OS.

**Comment by artomberus** [comment] 2020-10-21 18:30
> Do you use the same layout and system language on both Xubuntu 20.04 and Elementary OS?
I'm using Elementary OS with Russian locale, and combined layout (Russian+Ukrainian) + second built-in English layout. Xubuntu 20.04 uses Russian locale and Russian default (built-in) layout (and English built-in layout as second input language). 
> Hm, this is weird, I still can't reproduce it. Basically what's going on is that the text you entered is treated as invalid utf8.
This version, which I downloaded when I learned about the program, is guaranteed to work - fsearch-trunk_20200802+r508.0b6eff0_ubuntu18.04.1_amd64.deb
After that, I updated the program from the PPA several times, but, unfortunately, did not notice the specific version on which the program began to crash.

If I can provide more information, I will be glad. Your program replaces Everything for me, it is a "must have" software :) In addition, in the latest versions, the search has become much faster.

I added the built-in Russian layout to the Elementary OS, and tried to enter text into the search - the result is the same - an error. Which probably means it's not about the layout...

One more test ... Maybe you can figure out what's the matter:
When I write a word (Переводчик) in Mousepad and copy it into the search field, the program crashes. But if I copy the same word from translate.google.com.ua - the program works further, and I can even delete the word by letter.
If I type this word in the LibreOffice and copy it into the application search, everything is ok.
On other sites, it is a random reaction. On opennet.ru - word "новости" leads to crash, but the word "ФОРУМ" does not cause an error. And both of them are on the same page, which means, in theory, they have the same encoding...

I wrote all this before you updated the program. I will try the corrected version as soon as I update and write about the results, thanks :)

**Comment by cboxdoerfer** [comment] 2020-10-21 18:39
Thank you for the information!

> After that, I updated the program from the PPA several times, but, unfortunately, did not notice the specific version on which the program began to crash.

It probably happened when I fixed case insensitive search for languages like Turkic and Lithuanian, because that caused the change in the utf8 handling in FSearch.

> If I can provide more information, I will be glad. 

Could you please provide the output of `localectl status`? Preferably by both the Xubuntu and Elementary OS systems.

**Comment by artomberus** [comment] 2020-10-21 18:58
> Could you please provide the output of `localectl status`? Preferably by both the Xubuntu and Elementary OS systems.

For Elementary OS:
localectl status
   System Locale: LANG=ru_RU.UTF-8
       VC Keymap: us
      X11 Layout: us,ru,ua
     X11 Variant: ,,winkeys

For Xubuntu:
localectl status
   System Locale: LANG=ru_UA.UTF-8
                  LANGUAGE=ru_UA:ru
       VC Keymap: n/a
      X11 Layout: us,ru
       X11 Model: pc105
     X11 Variant: ,
     X11 Options: grp_led:scroll

> It probably happened when I fixed case insensitive search for languages like Turkic and Lithuanian, because that caused the change in the utf8 handling in FSearch.

Most likely it is. Glad that you are actively responding and fixing bugs that sometimes arise. Thanks :)

**Comment by cboxdoerfer** [comment] 2020-10-21 19:33
Even with Elementary OS I can't reproduce it, no matter which keyboard layout (russian or russian/ukrainian) or system language I use. So I hope the fix I mentioned early works, otherwise we probably need to do some more investigation.

**Comment by artomberus** [comment] 2020-10-22 07:29
@cboxdoerfer , Hello! I just updated. I can search using uppercase. The case is case sensitive (The program filters out the same letters, but in lower case - it does not show in the search).  Option "match case when request contains at least one uppercase character" activated. I can even search in small case, provided that the first character is in large. After a variety of tests, I can conclude that if the first character is in upper case (and, therefore, case is taken into account), the program does not crash. But when the first character is lowercase - the program crashes. But only for the Cyrillic alphabet. With Latin characters, there are no problems with lower case. I entered text manually, I also copied text from other applications - the result is consistently the same. Hope this clarifies something.

**Comment by cboxdoerfer** [comment] 2020-10-22 08:27
What terminal output do you now get when it crashes?

**Comment by artomberus** [comment] 2020-10-22 08:40
@cboxdoerfer , the same:
[search] ы
[search] token 0: ы
(fsearch:6505): GLib-CRITICAL **: 11:38:45.188: g_utf8_strdown: assertion 'str != NULL' failed
Ошибка сегментирования

**Comment by cboxdoerfer** [comment] 2020-10-22 08:45
Awesome thx! I have no idea why I didn't think of this sooner, but apparently it's not the search input that causes the crash, it's caused by particular file names. This also explains why I can't reproduce it and why it works fine on your Xubuntu system. I just pushed a fix, which not only should prevent the crash, but should also report the file names causing the bug.

**Comment by cboxdoerfer** [comment] 2020-10-22 08:48
If you want to try the fix immediately you can build FSearch from source for testing, which isn't complicated. Otherwise again the PPA will have the fix in the next 24 hours or so.

**Comment by artomberus** [comment] 2020-10-22 11:06
@cboxdoerfer , Thank you very much! I just followed all the building instructions - the program built, installed and successfully launched. I can search both in small and large cases, and the case is correctly considered. 
fsearch --version
FSearch 0.1beta4.436-69ed

But now the program does not write anything to the console at all. If you need (to understand the essence) to find out which files (names) caused the crash, then tell me how to call it so that the file names are in the log... Or build the previous version with the logging function. 

In any case, I am glad that I can continue to use FSearch.

**Comment by cboxdoerfer** [comment] 2020-10-22 11:18
Oh yes, within the fsearch directory (after closing running fsearch instances) do the following:

```
make clean
./configure --enable-debug
make && sudo make install
```

Now you should get debug output on the console and the file names with bad encoding should be reported as `[search] failed to normalize haystack: file name`. If you want it to show the full path, to find where those files are, you can need to enable the `Search in Path` option temporarily.

If you want to remove the manually build version tomorrow when the PPA is updated you just need to enter the fsearch directory again and run `sudo make uninstall`. This will only remove the manual build.

**Comment by artomberus** [comment] 2020-10-22 12:29
Did as you said.
Yes. I found it :)
failed to normalize haystack: CAMINH�O - P�RA-CHOQUE, ESCADA E ESCAPAMENTO COM RODA.jpg
This file is located in /home/dmitry/.local/share/supertuxkart/addons/tracks/las-dunas-stadium
It is a part of one of downloaded supertuxkart tracks from within the game itself.

Also I have such warning - (fsearch:20277): Pango-WARNING **: 15:15:47.715: Invalid UTF-8 string passed to pango_layout_set_text()



> If you want to remove the manually build version tomorrow when the PPA is updated you just need to enter the fsearch directory again and run `sudo make uninstall`. This will only remove the manual build.

Thank you! I'll do that.

**Comment by cboxdoerfer** [comment] 2020-10-22 14:36
Thx, the Pango warnings should now also be fixed.

**Comment by cboxdoerfer** [comment] 2020-10-22 14:54
And regarding the file which caused the bug, I don't think there's anything more I can do. Its file name uses an unsupported (or broken) character encoding, which means that case insensitive matching of this file might not always work properly. But just applies to this particular file.

**Comment by artomberus** [comment] 2020-10-22 15:45
@cboxdoerfer , I didn't even know about the existence of such a file :-) A good guess is yours that a particular file may cause the error. Now the program has become even more stable. It's great.
And I will most likely delete the file with the wrong name. Or remove the entire addon. It is possible, of course, to write to the add-on author, although this is unlikely to create problems elsewhere.
I've encountered files with naming problems before. This usually happened when the browser, or the download program, or the archiver did not correctly recognize the file name encoding.

Thanks for the help :-)

**Comment by cboxdoerfer** [comment] 2020-10-22 15:57
No problem :) I'm also very grateful that you spotted and reported that bug, because handling different character encodings without crashing was something I totally forgot. So it made FSearch better and more reliable, thx.

(Another side effect was that by trying out Elementary OS I noticed some bugs within the UI, which I'm going to fix soon.)

>Thanks for the help :-) Should I close the issue? I am completely new to GitHub.

In general you can close it when the issue was solved, but in this case I might just as well close it myself.

**Closed by cboxdoerfer** 2020-10-22 15:57 UTC
