### ISSUE TITLE
Cut Paste File or Directory.

### ISSUE THREAD

**Issue by blueray453** [cboxdoerfer/fsearch#151] opened 2018-12-12 18:23 UTC
When I right click a file, it gives copy option but not cut option.

I have to right click, go to the location, search for the file and then cut it.

Can you please add cut along side copy on the roadmap.

**Comment by Areahints** [comment] 2019-03-25 07:21
+1 for this functionality

**Comment by theorangeBirdybird** [comment] 2019-09-22 20:28
For some reason Ctrl+C or clicking the copy option doesn't work. My Clippboard always ends up empty.

**Comment by mbnoimi** [comment] 2019-12-09 09:23
+1

**Comment by AtilioA** [comment] 2020-07-26 17:42
This is one of the things I miss about Everything the most when using fsearch.

**Comment by AtilioA** [comment] 2020-07-26 17:42
This is one of the things I miss the most about Everything when using fsearch.

**Comment by cboxdoerfer** [comment] 2020-07-29 14:59
Closing, duplicate of #48. Discussion should continue there.

**Closed** 2020-07-29 15:00 UTC
Labels: enhancement
