### ISSUE TITLE
[Feature request] live indexing

### ISSUE THREAD

**Issue by Golddouble** [cboxdoerfer/fsearch#202] opened 2020-07-30 14:38 UTC
Until now, when we start FSearch, we always first have to update the database.

So wouldn't it be possible to add a daemon, that always updates automatically the database, as soon as the name of a file changes or a file is added or deleted?

**Comment by cboxdoerfer** [comment] 2020-07-30 17:12
Duplicate of #26 and #116, please use those issues for discussion. Closing.

**Closed by cboxdoerfer** 2020-07-30 17:12 UTC
